declare_args() {
  gnb_repo_dir = getenv("GNB_REPO_DIR")
}

declare_args() {
  gnb_exec = rebase_path("${gnb_repo_dir}/scripts/exec.py")
  gnb_which = rebase_path("${gnb_repo_dir}/scripts/which.py")
}

# package
import("${gnb_repo_dir}/gnbuild/package.gni")

# toolchain
import("${gnb_repo_dir}/gnbuild/toolchain.gni")

# project
declare_args() {
  project_name = "demo_stm32f103"
  project_profile = "apps"
  project_version = ""
}
