declare_args() {
  gnb_build_dir = rebase_path(getenv("MDS_REPO_DIR") + "/gnbuild")
}

# package
import("${gnb_build_dir}/package.gni")

# toolchain
import("${gnb_build_dir}/toolchain.gni")

# project
declare_args() {
  project_name = "demo_gd32e113"
  project_profile = "apps"
  project_version = ""
}
