pkggroup("stm32f1xx_device") {
  deps = [ "system_stm32f1xx" ]
}

executable("${project_name}") {
  sources = [ "apps_main.c" ]

  deps = [ ":stm32f1xx_device" ]

  inputs = [ rebase_path("STM32F103XB_FLASH_APPS.ld") ]
  ldflags = [ "-T" + rebase_path("STM32F103XB_FLASH_APPS.ld") ]

  ldflags += [ "-Wl,-Map=" + rebase_path("${root_out_dir}/${target_name}.map") ]
}

toolchain_action("${project_name}.dis") {
  script = "objdump"
  args = [
    "-SFhlx",
    rebase_path("${root_out_dir}/${project_name}.elf"),
    ">",
    rebase_path("${root_out_dir}/${target_name}"),
  ]
  deps = [ ":${project_name}" ]
  outputs = [ "${root_out_dir}/${target_name}" ]
}

toolchain_action("${project_name}.bin") {
  script = "objcopy"
  args = [
    "-Obinary",
    "-R.logstr",
    rebase_path("${root_out_dir}/${project_name}.elf"),
    rebase_path("${root_out_dir}/${target_name}"),
  ]
  deps = [ ":${project_name}" ]
  outputs = [ "${root_out_dir}/${target_name}" ]
}

toolchain_action("${project_name}.hex") {
  script = "objcopy"
  args = [
    "-Oihex",
    "-R.logstr",
    rebase_path("${root_out_dir}/${project_name}.elf"),
    rebase_path("${root_out_dir}/${target_name}"),
  ]
  deps = [ ":${project_name}" ]
  outputs = [ "${root_out_dir}/${target_name}" ]
}

toolchain_action("${project_name}.logstr") {
  script = "objcopy"
  args = [
    "-Obinary",
    "-j.logstr",
    rebase_path("${root_out_dir}/${project_name}.elf"),
    rebase_path("${root_out_dir}/${target_name}"),
  ]
  deps = [ ":${project_name}" ]
  outputs = [ "${root_out_dir}/${target_name}" ]
}

group("default") {
  deps = [
    ":${project_name}",
    ":${project_name}.bin",
    ":${project_name}.dis",
    ":${project_name}.hex",
    ":${project_name}.logstr",
  ]
}
