pkggroup("stm32h7xx_device") {
  deps = [ ":stm32h7xx_system" ]
}

pkggroup("drv_chip_stm32h7xx") {
}

pkggroup("mds_component") {
}

pkggroup("mds_kernel") {
}

source_set("board_src") {
  sources = []

  public_deps = [
    ":drv_chip_stm32h7xx",
    ":mds_component",
    ":mds_kernel",
    ":stm32h7xx_device",
  ]
}
